### ISSUE TITLE
won't compile; what do?

### ISSUE THREAD

**Issue by CarlBeek** [karalabe/minority#1]
I'll have you know my company is very important and we rely on this codebase. It is unacceptable that these kind of bugs are still in the latest release! How did this even pass QA?

My latest NFT will now drop late and you'll have to answer to the apes. How will the miners get their fees now?

#### System information

OS & Version: I use Arch BTW
Commit hash : `4b825dc642cb6eb9a060e54bf8d69288fbee4904`

#### Expected behaviour

Step 1. `$ git clone git@github.com:karalabe/minority.git; cd minority`
Step 2. `$ make`
Step 3. ?????
Step 4. Profit

#### Actual behaviour

```
$ make
make: *** No targets specified and no makefile found.  Stop.
```

#### Steps to reproduce the behaviour

```
$ make
```

**Comment by karalabe** [comment]
Dear `<FirstName>`,

We have received your issue `<IssueNumber>` and are very sorry to hear you have difficulties running `<ProductName>`. Please rest assured that every single issue is **personally** read and responded to by our team. The satisfaction of `<UserCompany>` is our top priority!

Kind regards,
  `<CustomerSupportName>`
  
 `// TODO: Form doesn't fill. Can we generate random support names?`

**Comment by ec2** [comment]
i had the same issue @CarlBeek. have you tried installing gentoo? it worked for me

**Comment by karalabe** [comment]
Works on his^ machine.
